### ISSUE TITLE
Issue while tuning XgemmDirectTT

### ISSUE THREAD

**Issue by ari-wwu** [CNugteren/CLBlast#140]
I have issues while tuning the single precision XgemmDirectTT kernel on an Intel(R) Xeon(R) CPU E5-1620 v2 @ 3.70GHz CPU: for most tuning parameter configurations, I get a segmentation fault for unknown reasons.

For example, regarding the the kernel input

```
100, // kSizeM
500, // kSizeN
800, // kSizeK
1,                     // alpha
0,                     // beta
buffer of floats and size (kSizeM * kSizeK),
0,                     // offset M
800                 // a_ld
buffer of floats and size (kSizeK * kSizeN),
0,                     // offset N
800                 // b_ld
buffer of floats and size (kSizeM * kSizeN),
0,                     // offset K
500,                // c_ld
1,                     // c_transpose
0,                     // a_conjugate
0                      // b_conjugate
```
and the parameter configuration

```
KWID=2   
MDIMAD=8   
MDIMCD=8   
NDIMBD=8
NDIMCD=8
PADA=0  
PADB=0  
PRECISION=32 
VWMD=1   
VWND=1
WGD=8  

PRECISION=32
```

which lead to a thread configuration of

```
global size = (104,504,1) , 
local size = (8,8,1)
```

then I get a segmentation fault although all parameter constraints are fulfilled. 

BTW: on the systems's NVIDIA Tesla K20c GPU, I have no issues with the above tuning parameter configuration and kernel input.

**Comment by CNugteren** [comment]
I tried to reproduce your issue, but I saw that the included CLBlast tuner doesn't support a custom `ld` argument, so I suppose you are running your own custom code? If so, this issue might not necessarily be an issue with CLBlast then!

One curious thing I noticed are your `ld` arguments. Are they correct? Because they don't make much sense to me given your `m`, `n`, and `k` values! Better perhaps to make sure they are correct first (e.g. running the CLBlast client program with those arguments), and then try to tune.

**Comment by ari-wwu** [comment]
Sorry, of course you are right. I had typos in the arguments above (they are now corrected). The issue occurs with the  kernel arguments

```
100, // kSizeM
500, // kSizeN
800, // kSizeK
1,                     // alpha
0,                     // beta
buffer of floats and size (kSizeM * kSizeK),
0,                     // offset M
800                 // a_ld
buffer of floats and size (kSizeK * kSizeN),
0,                     // offset N
800                 // b_ld
buffer of floats and size (kSizeM * kSizeN),
0,                     // offset K
500,                // c_ld
1,                     // c_transpose
0,                     // a_conjugate
0                      // b_conjugate
```
the parameter configuration

```
KWID=2   
MDIMAD=8   
MDIMCD=8   
NDIMBD=8
NDIMCD=8
PADA=0  
PADB=0  
PRECISION=32 
VWMD=1   
VWND=1
WGD=8  

PRECISION=32
```

and the thread configuration

```
global size = (104,504,1) , 
local size = (8,8,1)
```

**Comment by CNugteren** [comment]
OK, but how do you test this? And why don't you use the normal tuners? I wouldn't know how to reproduce this, because the CLBlast tuner doesn't allow setting a specific `ld` value and also doesn't support `m`, `n`, `k`, values that are not a multiple of the local workgroup size. The CLBlast client perhaps with some manually set parameters? I think it's still not clear this is a CLBlast issue!

**Comment by ari-wwu** [comment]
The ``XgemmDirectTT`` kernel was called with this parameters from [Caffe](https://github.com/rickyHong/caffe-for-clblast-branch). I try to tune the tuning-parameters for exactly that input size of the kernel, thats why I don't use the tuner as recommended.

**Comment by CNugteren** [comment]
Sorry for my late reply, but I now managed to reproduce your issue with the tuners included in the CLBlast repository itself. I modified [CLTune](https://github.com/CNugteren/CLTune) to now automatically set a proper global size if the global size is not a multiple of the local size.

If I now run `./clblast_tuner_xgemm_direct -m 100 -n 500 -k 800` on my Intel GPU using Beignet, everything seems fine. If I run it on my Intel CPU then I get segfaults at unpredictable times. Not sure what's causing this yet - I will investigate.

Could you double check if you can also reproduce this behaviour now with the latest version of CLTune and the above command to run the `clblast_tuner_xgemm_direct` tuner? Thanks!

**Comment by CNugteren** [comment]
Could you re-try with the latest master? I've fixed issue #167 and I believe it also fixes your issue. At least, the above example (`./clblast_tuner_xgemm_direct -m 100 -n 500 -k 800`) now runs fine on my machine - and it didn't before. Keep in mind that for that you'll need the latest CLTune as well.

**Comment by CNugteren** [comment]
I'm closing this issue now since I was able to reproduce it and fix on my machine (see above). @ari-wwu: If  you still experience this issue please re-open it and let me know what you tried and what didn't and what did work.
