### ISSUE TITLE
TRSM crashes after dozen seconds

### ISSUE THREAD

**Issue by blueberry** [CNugteren/CLBlast#207]
Hi Cedric,

I am not able to run *any*, even the simplest example TRSM with CLBlas on AMD R9 290X (haven't tried on other hardware).

I am not able to post a C/C++ code, since I am using it through JOCLBlast (Java) and Neanderthal (Clojure), but it seems to me that either I am making a dumb mistake in calling it, which is fairly automatized, since I integrated most of the rest of JOCLBlast in the same way, and it works well, or perhaps TRSM does not work at all.

Here's how to reproduce it: Create any simple triangular system. I used

```
A = [1 2 3 | 0 -1 -2 | 0 0 1] (triangular lower column-major)
B = [-1 -1 0.5]
Result = [-1 -1 1.5]
```
I am unable to get the result with JOCLBlast/CLBlast. There is activity for some time, but it never finishes, and eventually crashes the JVM.

Now, why do I think that this should work?
1. The rest of CLBlast works like a charm with my infrastructure.
2. I tried the same example with my JCublas engine (Clojure -> Java -> cuBlas) and it works swiftly and gives me the the same result as the CPU engine based on MKL.

Did you test TRSM, and, if so, can you point me to a (C/C++) example of how to use it in CLBlast? Maybe there is some gotcha that I am not aware of...

Thank you one more time for CLBlas -> amazing free library!

**Comment by blueberry** [comment]
Here's the core dump if it's of any help. @CNugteren @gpu 
[hs_err_pid4966.log](https://github.com/CNugteren/CLBlast/files/1415911/hs_err_pid4966.log)

**Comment by gpu** [comment]
Can you reconstruct the exact call?  There are quite a few arguments involved...

    const CLBlastLayout layout, 
    const CLBlastSide side, 
    const CLBlastTriangle triangle, 
    const CLBlastTranspose a_transpose, 
    const CLBlastDiagonal diagonal,
    const size_t m, 
    const size_t n,
    const float alpha,
    const cl_mem a_buffer, 
    const size_t a_offset, 
    const size_t a_ld,
    cl_mem b_buffer, 
    const size_t b_offset, 
    const size_t b_ld,
    cl_command_queue* queue, 
    cl_event* event

I'd give it a try, probably by adjusting one of the existing samples, but am not sure about the arguments right now.

**Comment by blueberry** [comment]
https://github.com/uncomplicate/neanderthal/blob/master/src/clojure/uncomplicate/neanderthal/internal/device/clblast.clj#L497

The arguments should be almost the same as in trmm. 

Actually, *any* working example would help me by confirming whether this function works at all. I will do my homework and explore where I'm wrong if it does :) In MKL and cublas, it worked with no problems.

**Comment by gpu** [comment]
There are tests for this function in CLBlast, although I'll have to check out CLBLAS to compile and run them (as CLBLAS is used as a reference). But even then, the call seems to be somewhat "automated", so that I'm not sure whether I could create an example from that. Similarly, for the neanderthal version: This only is the function declaration. I was wondering about the actual *call*, i.e. the exact configuration of the first 5 parameters, as well as the `ld_` parameters. (I could imagine that using a wrong parameter here would mess up things severely).

**Comment by blueberry** [comment]
@gpu I extracted the actual argument values in this hash-map printout {:key value}:
```
{ :layout 102, 
  :side 141,  
  :triangle 122, 
  :diagonal 131, 
  :a_transpose 111, 
  :m 5, 
  :n 3, 
  :alpha 1.0, 
  :a_buffer #object[org.jocl.cl_mem 0x3e2b967c cl_mem[0x7fa68411b760]], 
  :a_offset 0, 
  :a_ld 5, 
  :b_buffer #object[org.jocl.cl_mem 0x66791e6d cl_mem[0x7fa64805ca30]], 
  :b_offset 0, 
  :b_ld 5
  :cl_queue #object[org.jocl.cl_command_queue 0x266a17d0 cl_command_queue[0x7fa684432cb0]], 
  :cl_event nil}
```

Thank you for looking into this.

**Comment by blueberry** [comment]
... and the content of the matrices is in this test code:

https://github.com/uncomplicate/neanderthal/blob/master/test/uncomplicate/neanderthal/real_test.clj#L2269

**Comment by CNugteren** [comment]
I there. I'll take a look into this issue tonight. Some remarks until then:
* If you compile CLBlast in verbose mode (`-DVERBOSE=ON` to CMake) you'll get messages when a kernel starts and ends, so that will help the debugging to find out whether the issue is in a kernel (and in which) or in the host code.
* You can compile and run the tests without having to have clBLAS installed, a regular CPU BLAS library (e.g. openblas, atlas, MKL, etc.) is also fine.
* I've fixed an issue two days ago regarding TRSM. Not sure if related at all, but [here is the fix](https://github.com/CNugteren/CLBlast/commit/d49aae236eca2dddc3228791ec367cc0c9d3bc7e) (now in master).
* If you are using the interface incorrectly it should return an error code, so this is a bug anyway in CLBlast. I'll investigate by making a small C++ example first.

**Comment by blueberry** [comment]
I recompiled CLBlast, built new JOCLBlast snapshot, and updated my lib to use it, and the problem still persists, unfortunately.

**Comment by CNugteren** [comment]
I've just added an example using TRSM from C++: 8579b2b.

I've also fixed some other minor issues in TRSM while working on another bug.

I should also note that the TRSM routine contains kernels which are not tuned. That means they might well use some configuration of work-groups or local memory which is not supported by the hardware. But that should still result in a proper error normally. Perhaps that's what's going on? Can you test on another machine perhaps? And have you run the CLBlast included tests?

**Comment by blueberry** [comment]
@CNugteren @gpu 

TRSM actually works on the Intel CPU through AMD's platform! It crashes when run on the AMD GPU. I'm using the closed-source catalyst drivers, since the latest amdgpu-pro and ROCm from AMD do not (yet) support OpenCL 2.0 in the host code.

I've tried it both through Java, and as part of CLBlast tests. The result is the same.

When called from JVM, CPU returns the correct result, while GPU works for several seconds, and then crashes the JVM and prints the core dump.

When called as clblast_test_xtrsm, CPU prints the report (in which tests are reported as skipped) and finishes normally. GPU, on the other hand, segfaults.

Now, something curious is happening. When I tried clblast tests, I first run a test on the CPU (with -device 2). Then, I run the GPU, and it segfaulted. I then run the other GPU (device 1), and it freezed my machine, so I had to reboot. After the reboot, all clblast test segfault, but when run from the JVM, clblast works as normal (the GPU xtrsm still crashes though).

**Comment by CNugteren** [comment]
OK, so it is an issue of the AMD GPU and it occurs in the C++ code as well.

The TRSM routine is still marked as experimental in the README, since it contains kernels not being tuned. Instead, these kernels use fixed values for work-group sizes and local memory sizes. With this being the case, it might well be too much for certain devices. I propose to solve this issue by making the TRSM (and TRSV) kernels part of the tuning infrastructure. I guess in that case tuning for your device will result in usable parameters which do not make your system crash :-)

**Comment by blueberry** [comment]
Thanks for clearing that. I just do not share the optimism that it is (only) a tuning issue, since R9 290X is (still) a quite powerful card, and the problem I tried is rather trivial. Anyway, I'll try to tune this as soon as possible, and test to see whether there is an improvement.

**Comment by CNugteren** [comment]
I just took a quick look at the kernels involved but it seems like making them tuneable isn't trivial, so I will have to post-pone this and look at it later when I have more time.

In the meantime, could you output your `clinfo` or `clblast_test_diagnostics` output so we can try to find out what the limiting factor of your R9 290X is?

**Comment by CNugteren** [comment]
A similar issue with the TRSM routines and the AMD OpenCL compiler was recently reported and solved in #229. Could you have a go with the latest CLBlast master and see whether your issue is resolved as well? Thanks!

**Comment by blueberry** [comment]
Thank you very much, Cedric. I am not able to do it right now. I expect to be able to try this in a few weeks.

**Comment by CNugteren** [comment]
OK, no worries. Let me know when you know more.

**Comment by CNugteren** [comment]
@blueberry Did you perhaps found the time to test this again to see if the issue is resolved? Thanks!

**Comment by blueberry** [comment]
@CNugteren Sorry, I got distracted by other work and completely forgot about this. Thanks for reminding me.

As I should also build JOCLBlast 1.3.0 for linux soon (sorry for being late on that, @gpu, I had lots of other stuff to do lately), I'll go through the changelog, and enable and test those features in neanderhtal.

**Comment by blueberry** [comment]
I can confirm that TRSM now works and does not hang.  There is an issue, though, with (maybe) giving wrong results when there are exotic combinations of layouts and diagonals, though. However, I have solved this by just using ColMajor layout, and calculating other parameters according to that, in the same way I do with cuBLAS (which does not support layout in this method). 

Not only this is solved, but the whole setup of CLBlast is now much faster. I guess this has to do with the recent changes of architecture. Congratulations!
