### ISSUE TITLE
Resource cleanup issue

### ISSUE THREAD

**Issue by 9prady9** [CNugteren/CLBlast#292]
We have recently made CLBlast the default upstream for BLAS functionality in https://github.com/arrayfire/arrayfire after which we have been experiencing segfaults from all unit tests that use blas functions on Windows.

Debugging the problem further led us to believe that this issue is similar to the resource cleanup issue we faced with clBLAS. With clBLAS(the earlier default BLAS upstream for ArrayFire), we skipped calling the tear down function to let OpenCL driver handle the cleanup on Windows. 

With CLBlast, we tried the following but we didn't progress that much towards resolving the issue.
- `CLBlastClearCache()` - I didn't find an equivlanet function in c++ API but tried it in our cleanup section to confirm it's effect but that didn't help. Is there a way to do this in C++ API ? - to remove all cached programs/kernels from CLBlast.
- We want to leak the resources the same way as we do with clBLAS but we didn't find any related API calls to achieve that as well.

On the whole, we want to be able to cleanup/leak CLBlast allocated kernels/programs so that either ArrayFire/OpenCL-driver will take care of that. Any suggestions to achieve that are greatly appreciated.

Note: Running arrayfire unit tests manually(not via a test suite framework) might make it look like they are running fine as they don't crash at exit but return a non-zero exit code.

**Comment by CNugteren** [comment]
OK, that should be fixed indeed.

First of all, the C++ API to clean up the cache is simply `ClearCache()` found [here](https://github.com/CNugteren/CLBlast/blob/master/include/clblast.h#L687). Second, the only thing CLBlast keeps as a global state is the cache. So cleaning that up should resolve everything, am I right? But I would say that even that is not necessary, as the OpenCL driver should be able to handle that properly when the C++ program is cleaned-up.

That said, there are some related issues recently:

1. There is a bug in Intel's new NEO driver, but it is reported and will hopefully be solved. See more details [this issue](https://github.com/CNugteren/CLBlast/issues/276).

2. There are several issues reported on Windows, but never really solved it seemed. One [issue was closed due to inactivity](https://github.com/CNugteren/CLBlast/issues/203) and another [was solved by moving to VS 2015](https://github.com/CNugteren/CLBlast/issues/273). Perhaps the discussion in those threads might help you?

**Comment by 9prady9** [comment]
Interesting I missed it somehow in the C++ header. Thanks for the pointer.

The stack trace points to Program object destructor. I believe the root cause to be as follows: `CLBlast` cache is being cleared out after ArrayFire's objects are.

The problem is not with an Intel device, it is happening on a NVIDIA card too. I have gone over the issues you mentioned and that didn't help. I can try to use `ClearCache` instead of the C-API call and see if it does work. But I would assume C++ API is merely delegating to C-API, is that right ?

**Comment by 9prady9** [comment]
The other alternative is to leak the resource(Cache/Database from CLBlast) on windows. If not as a general fix in CLBlast, we would like to know what files to touch upon to achieve that so that we can apply it as a patch on our end.

**Comment by CNugteren** [comment]
> I believe the root cause to be as follows: CLBlast cache is being cleared out after ArrayFire's objects are

I don't see why this would be an issue?

> I have gone over the issues you mentioned and that didn't help.

Have you commented out the program object destructor in `clpp11.hpp` to see if that indeed solves the issue?

> But I would assume C++ API is merely delegating to C-API

Yes, it does the same thing indeed.

> ClearCache call inside our cleanup routine didn't help either

Then something is wrong. It should clean up everything in the cache. I will take a look at this soon myself, but I'm a bit busy right now. Perhaps in a week or so?

**Comment by umar456** [comment]
I have debugged this issue several times on Windows. The issue stems from the order of the unloading of modules in a Windows application. The destructors of the cl::Program objects are called after the OpenCL drivers are unloaded. This, in turn, causes an invalid memory access when the clReleaseProgram is called because the underlying resource has already been freed.

I was able to get around this by modifying the cl::Program destructor to avoid that call. I am not sure if this is something you want to do in your library or if this is something we should do in ArrayFire. Here is the diff:

```
diff --git a/src/clpp11.hpp b/src/clpp11.hpp
index ce6f39c..c509220 100644
--- a/src/clpp11.hpp
+++ b/src/clpp11.hpp
@@ -463,7 +463,7 @@ class Program {

   // Clean-up
   ~Program() {
-    if (program_) { CheckErrorDtor(clReleaseProgram(program_)); }
+    if (program_) { /*CheckErrorDtor(clReleaseProgram(program_));*/ }
   }

   // Compiles the device program and checks whether or not there are any warnings/errors
```

**Comment by CNugteren** [comment]
Something like [this commit](https://github.com/CNugteren/CLBlast/commit/7b416c8686f7cc83c79c886e24851db33baacf80) was previously made as test for one of the issues I mentioned above, but eventually was removed. I can re-add that if that indeed fixes it. But it should also be solved by calling `ClearCache()` before the OpenCL driver is unloaded, which will call all the `clReleaseProgram`s in time.

Could you double check if both methods work? I can still add the fix of course, but I want to be sure the `ClearCache()` functionality works as expected, perhaps it contains a bug.

**Comment by 9prady9** [comment]
I have tried `ClearCache` already and it doesn't work.

If you can build arrayfire(just opencl backend would do), you can modify the externally cloned clblast project( cmake clones it under `<build>\third_party` to verify my claim.

**Comment by umar456** [comment]
We have tried to call `ClearCache` in one of our destructor classes but the issue is not resolved because that destructor is called after the OpenCL runtime is unloaded. The only way we can get `ClearCache` working is by creating a function that users call before main exits the program. This approach is somewhat inconveneint for our users and we are trying to avoid it. This might be something we need to consider if you don't want to introduce this in your library or we can maintain this in our fork.

**Comment by CNugteren** [comment]
Ok, I'll re-add the removal to the library. Only msvc, right? So like https://github.com/CNugteren/CLBlast/commit/7b416c8686f7cc83c79c886e24851db33baacf80

**Comment by umar456** [comment]
I am not sure if this is a compiler or an OS issue. We base our checks on windows builds but never really tried clang or icc on windows. MSVC is probably fine.

**Comment by CNugteren** [comment]
OK, let's do it like this for now:
https://github.com/CNugteren/CLBlast/pull/295

**Comment by 9prady9** [comment]
The concerned ArrayFire unit tests pass with the change. Thank you!

**Comment by CNugteren** [comment]
Is everything working OK now? Shall we close this issue or is there still something I should do?

**Comment by CNugteren** [comment]
Apart from the bug you reported here, there was another serious bug. So I decided to release a new 1.4.1 release. Perhaps you'd want to update ArrayFire to use that version. It includes the fix for the bug discussed here of course.

**Comment by 9prady9** [comment]
@CNugteren Sure, thanks for the update.
